Operator API
temporalio/api-go pull request #89
Opened 2022-02-14 16:03 UTC by Spikhalskiy

2022-02-14 17:02 UTC, cretz commented
This repository's contents are auto-generated/merged when PRs from https://github.com/temporalio/api are merged. You do not need manual PRs.

2022-02-14 17:13 UTC, Spikhalskiy commented
@cretz I need the auto-generated content in this branch to be able to reference this branch in temporal/temporal without merging anything. I'm going to clean up generated changes when these PRs will be ready for review and merge.

2022-02-17 01:21 UTC, alexshtin requested changes
Please don't merge it.

2022-02-23 02:47 UTC, alexshtin approved these changes

2022-02-23 03:23 UTC, merged